export * from './categories';
export * from './footer-links';
export * from './legals';
export * from './products';
export * from './nav-links';
export * from './pizzerias';
export * from './promos';
export * from './sberbank';
export * from './slides';
