import { MenuItemTypes } from "@/types";
import porkRoast from "../public/assets/images/pizza-pork-roast.webp";
import americana from "../public/assets/images/pizza-americana.webp";
import caesar from "../public/assets/images/pizza-caesar.webp";
import carbonara from "../public/assets/images/pizza-carbonara.webp";
import chickenBlueCheese from "../public/assets/images/pizza-chicken-blue-cheese.webp";
import chickenSausages from "../public/assets/images/pizza-chicken-sausages.webp";
import classic from "../public/assets/images/pizza-classic.webp";
import country from "../public/assets/images/pizza-country.webp";
import donKebab from "../public/assets/images/pizza-don-kebab.webp";
import fourCheeses from "../public/assets/images/pizza-four-cheeses.webp";
import fourSeasons from "../public/assets/images/pizza-four-seasons.webp";
import hamBacon from "../public/assets/images/pizza-ham-bacon.webp";
import hawaii from "../public/assets/images/pizza-hawaii.webp";
import hunter from "../public/assets/images/pizza-hunter.webp";
import julien from "../public/assets/images/pizza-julien.webp";
import margarita from "../public/assets/images/pizza-margarita.webp";
import meatHit from "../public/assets/images/pizza-meat-hit.webp";
import meat from "../public/assets/images/pizza-meat.webp";
import pepperoni from "../public/assets/images/pizza-pepperoni.webp";
import ranch from "../public/assets/images/pizza-ranch.webp";
import sizzlingBarbecue from "../public/assets/images/pizza-sizzling-barbecue.webp";
import chickenBurger from "../public/assets/images/pizza-chicken-burger.webp";
import cheese from "../public/assets/images/pizza-cheese.webp";
import italian from "../public/assets/images/pizza-italian.webp";

import mozzarella from "../public/assets/images/adds-mozzarella.png";
import onionGreen from "../public/assets/images/adds-onion-green.png";
import bacon from "../public/assets/images/adds-bacon.png";
import onionBulb from "../public/assets/images/adds-onion-bulb.png";
import cheeseSide from "../public/assets/images/adds-cheese-side.png";
import heart from "../public/assets/images/adds-heart.png";
import jalapeno from "../public/assets/images/adds-jalapeno.png";
import tomato from "../public/assets/images/adds-tomato.png";
import champignon from "../public/assets/images/adds-champignon.png";
import chickenSmoked from "../public/assets/images/adds-chicken-smoked.png";
import ham from "../public/assets/images/adds-ham.png";
import huntingSausages from "../public/assets/images/adds-hunting-sausages.png";
import pickledCucumbers from "../public/assets/images/adds-pickled-cucumbers.png";
import cheeseParmesan from "../public/assets/images/adds-cheese-parmesan.png";
import cheeseChedder from "../public/assets/images/adds-cheese-chedder.png";
import pimiento from "../public/assets/images/adds-pimiento.png";
import dill from "../public/assets/images/adds-dill.png";
import garlic from "../public/assets/images/adds-garlic.png";
import roastPork from "../public/assets/images/adds-roast-pork.png";
import onionFree from "../public/assets/images/adds-onion-free.png";
import pineapple from "../public/assets/images/adds-pineapple.png";
import cheeseBlue from "../public/assets/images/adds-cheese-blue.png";
import cheeseFeta from "../public/assets/images/adds-cheese-feta.png";
import sauce from "../public/assets/images/adds-sauce.png";

import bear from "../public/assets/images/cat-bear.webp";
import fire from "../public/assets/images/cat-fire.webp";
import leaf from "../public/assets/images/cat-leaf.webp";

export const menu: MenuItemTypes[] = [
  {
    id: 0,
    title: "Пицца ЧикенБургер",
    image: chickenBurger,
    ingredients:
      "Копченая курица, моцарелла, маринованные огурцы, болгарский перец, красный лук, соус бургер Heinz, фирменный томатный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      { id: 3, image: tomato, name: "Томаты", weight: 25, price: 25 },
      {
        id: 4,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 5, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 6,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 7, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 8, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 9,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 10,
        image: pimiento,
        name: "Болгарский Перец",
        weight: 17,
        price: 25,
      },
      {
        id: 11,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 12,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 13,
        image: roastPork,
        name: "Буженина",
        weight: 30,
        price: 45,
      },
      {
        id: 14,
        image: onionFree,
        name: "Лук Фри",
        weight: 10,
        price: 10,
      },
      {
        id: 15,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Соус Бургер на пиццу",
        weight: 23,
        price: 35,
      },
    ],
    removeIngredients: [
      "Копченая Курица",
      "Огурцы Маринованные",
      "Лук Репчатый",
      "Болгарский Перец",
      "Соус Бургер",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 10.7,
      fats: 7.64,
      carbohydrates: 31.37,
      calories: 237.06,
    },
  },
  {
    id: 1,
    title: "Пицца Итальянская",
    image: italian,
    ingredients:
      "Пепперони, два вида сыра моцареллы, шампиньоны, фирменный томатный соус, базилик, орегано, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      {
        id: 2,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 3, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 23,
        price: 45,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 14,
        image: cheeseBlue,
        name: "Сыр Блю Чиз",
        weight: 15,
        price: 55,
      },
      {
        id: 15,
        image: pimiento,
        name: "Болгарский Перец",
        weight: 17,
        price: 25,
      },
      {
        id: 16,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 17,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 18,
        image: roastPork,
        name: "Буженина",
        weight: 30,
        price: 45,
      },
      {
        id: 19,
        image: onionFree,
        name: "Лук Фри",
        weight: 10,
        price: 10,
      },
      {
        id: 20,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 21,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 22,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 23,
        image: sauce,
        name: "Соус Бургер на пиццу",
        weight: 23,
        price: 35,
      },
    ],
    removeIngredients: ["Шампиньоны", "Пепперони"],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 13.02,
      fats: 11.36,
      carbohydrates: 34.41,
      calories: 291.98,
    },
  },
  {
    id: 2,
    title: "Пицца Запечённая Буженина",
    image: porkRoast,
    ingredients:
      "Буженина из свинины, моцарелла, маринованные огурцы, лук фри, лук красный, майонезный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 10, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 11, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 12,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 13,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 14,
        image: porkRoast,
        name: "Буженина",
        weight: 30,
        price: 45,
      },
      {
        id: 15,
        image: onionFree,
        name: "Лук Фри",
        weight: 10,
        price: 10,
      },
      {
        id: 16,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
    ],
    removeIngredients: [
      "Огурцы Маринованные",
      "Лук Репчатый",
      "Буженина",
      "Лук Фри",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 9.98,
      fats: 13.21,
      carbohydrates: 34.18,
      calories: 295.5,
    },
  },
  {
    id: 3,
    title: "Пицца Мясной Хит",
    image: meatHit,
    ingredients:
      "Ветчина, буженина из свинины, охотничьи колбаски, моцарелла, фирменный томатный соус, майонезный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 10,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 14,
        image: pimiento,
        name: "Болгарский перец",
        weight: 17,
        price: 25,
      },
      {
        id: 15,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 16,
        image: roastPork,
        name: "Буженина",
        weight: 30,
        price: 45,
      },
      {
        id: 17,
        image: onionFree,
        name: "Лук Фри",
        weight: 5,
        price: 15,
      },
      {
        id: 18,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 20,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 21,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Ветчина", "Охотничьи Колбаски", "Буженина"],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 11.3,
      fats: 12.6,
      carbohydrates: 35.85,
      calories: 301.8,
    },
  },
  {
    id: 4,
    title: "Пицца Курица и Колбаски",
    image: chickenSausages,
    ingredients:
      "Копченая курица, охотничьи колбаски, моцарелла, маринованные огурцы, томаты, красный лук, свежий укроп, майонезный соус, кетчуп, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      {
        id: 8,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 9,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 10, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 11,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 12,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 13,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 14,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Томаты",
      "Копченая Курица",
      "Охотничьи Колбаски",
      "Огурцы Маринованные",
      "Лук Репчатый",
      "Укроп",
      "Майонезный соус",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 9.88,
      fats: 11.58,
      carbohydrates: 29.88,
      calories: 263.26,
    },
  },
  {
    id: 5,
    title: "Пицца Курочка Блю Чиз",
    image: chickenBlueCheese,
    ingredients:
      "Много курицы, моцарелла, сыр блю чиз с голубой плесенью, соус ранч, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      { id: 10, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 11, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 12,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 13,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 14,
        image: pineapple,
        name: "Ананасы",
        weight: 20,
        price: 25,
      },
      {
        id: 15,
        image: cheeseBlue,
        name: "Сыр Блю Чиз",
        weight: 15,
        price: 55,
      },
    ],
    removeIngredients: [
      "Сыр Моцарелла",
      "Копченая Курица",
      "Соус Ранч",
      "Сыр Блю Чиз",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 13.06,
      fats: 13.84,
      carbohydrates: 34.92,
      calories: 316.47,
    },
  },
  {
    id: 6,
    title: "Пицца Классика",
    image: classic,
    ingredients:
      "Ветчина, пепперони, моцарелла, пармезан, шампиньоны, фирменный соус томатный, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 11,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 12, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 13, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 14,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 15,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 16,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 17,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 18,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Сыр Моцарелла",
      "Шампионьоны",
      "Ветчина",
      "Пепперони",
      "Сыр Пармезан",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 13.47,
      fats: 12.34,
      carbohydrates: 32.93,
      calories: 296.61,
    },
  },
  {
    id: 7,
    title: "Пицца Жюльен",
    image: julien,
    ingredients:
      "Бекон, копчёная курица, моцарелла, чеддер, свежие шампиньоны, сливки, укроп, майонезный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 10,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 14,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 15,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Шампиньоны",
      "Копченая Курица",
      "Бекон",
      "Сыр Чеддер",
      "Укроп",
      "Майонезеный соус",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 12.86,
      fats: 15.43,
      carbohydrates: 32.77,
      calories: 321.35,
    },
  },
  {
    id: 8,
    title: "Пицца Ветчина и бекон",
    image: hamBacon,
    ingredients:
      "Ветчина, бекон, моцарелла, чеддер, красный лук, соус цезарь, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 10,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 14,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 15,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 16,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 17,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 20,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Ветчина", "Бекон", "Лук Репчатый", "Сыр Чеддер"],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 13.04,
      fats: 14.2,
      carbohydrates: 35.86,
      calories: 323.37,
    },
  },
  {
    id: 9,
    title: "Пицца Американа",
    image: americana,
    ingredients:
      "Бекон, моцарелла, чеддер, маринованные огурцы, фирменный томатный соус, медово - горчичный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 10, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 11, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 12,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 13,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 14,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 15,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Бекон",
      "Огурцы Маринованные",
      "Сыр Чеддер",
      "Горчичный соус",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 12.37,
      fats: 11.46,
      carbohydrates: 35.39,
      calories: 294.17,
    },
  },
  {
    id: 10,
    title: "Пицца Цезарь",
    image: caesar,
    ingredients:
      "Копчёная курица, салат айсберг, моцарелла, пармезан, томаты, соус цезарь, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      {
        id: 5,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 6, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 7, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 8,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      { id: 9, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 10,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 11,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 12,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 13,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Томаты",
      "Копченая Курица",
      "Сыр Пармезан",
      "Листья Салата",
    ],
    categories: ["Подходит для Детей"],
    categoryImages: [bear],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 11.84,
      fats: 10.36,
      carbohydrates: 32.09,
      calories: 268.95,
    },
  },
  {
    id: 11,
    title: "Пицца Дон Кебаб",
    image: donKebab,
    ingredients:
      "Копченая курица, моцарелла, свежие огурцы, томаты, красный лук, салат айсберг, свежий укроп, кетчуп, майонезный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 11,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 12, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 13, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 14,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 15,
        image: pimiento,
        name: "Болгарский перец",
        weight: 17,
        price: 25,
      },
      {
        id: 16,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 17,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 20,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Томаты",
      "Копченая Курица",
      "Огурцы Свежие",
      "Лук Репчатый",
      "Укроп",
      "Листья Салата",
      "Соус Кетчуп",
    ],
    categories: ["Подходит для Детей"],
    categoryImages: [bear],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 9.38,
      fats: 9.57,
      carbohydrates: 29.77,
      calories: 242.68,
    },
  },
  {
    id: 12,
    title: "Пицца Гавайская",
    image: hawaii,
    ingredients:
      "Много бекона, моцарелла, ананасы, фирменный томатный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      {
        id: 5,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 6, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 7, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 8,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      { id: 9, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 10, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 11,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 12,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 13,
        image: pineapple,
        name: "Ананасы",
        weight: 20,
        price: 25,
      },
      {
        id: 14,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 15,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Бекон", "Ананасы"],
    categories: ["Подходит для Детей"],
    categoryImages: [bear],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 12.08,
      fats: 9.62,
      carbohydrates: 36.52,
      calories: 280.95,
    },
  },
  {
    id: 13,
    title: "Пицца Охотничья",
    image: hunter,
    ingredients:
      "Пепперони, охотничьи колбаски, моцарелла, свежие шампиньоны, свежий укроп, соус ранч, фирменный томатный соус, тест",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 11,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 12, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 13, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 14,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 15,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Шампиньоны",
      "Пепперони",
      "Охотничьи Колбаски",
      "Укроп",
      "Соус Ранч",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 11.78,
      fats: 11.94,
      carbohydrates: 32.97,
      calories: 313.43,
    },
  },
  {
    id: 14,
    title: "Пицца 4 сезона",
    image: fourSeasons,
    ingredients:
      "Фирменный томатный соус, моцарелла, пепперони, ветчина, охотничьи колбаски, буженина из свинины, сыр блю чиз, сыр фета, томаты",
    price: 579,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 50,
        price: 50,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 25,
        price: 25,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 50, price: 35 },
      {
        id: 5,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 50,
        price: 65,
      },
      { id: 6, image: pepperoni, name: "Пепперони", weight: 37, price: 65 },
      { id: 7, image: bacon, name: "Бекон", weight: 32, price: 55 },
      {
        id: 8,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 30,
        price: 45,
      },
      { id: 9, image: onionBulb, name: "Лук Репчатый", weight: 15, price: 10 },
      { id: 10, image: onionGreen, name: "Зеленый Лук", weight: 15, price: 35 },
      {
        id: 11,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 55,
      },
      {
        id: 12,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 40,
        price: 65,
      },
      {
        id: 13,
        image: pineapple,
        name: "Ананасы",
        weight: 40,
        price: 45,
      },
      {
        id: 14,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 15,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
    ],
    removeIngredients: [
      "Томаты",
      "Копченая Курица",
      "Ветчина",
      "Пепперони",
      "Охотничьи Колбаски",
      "Сыр Фета",
      "Буженина",
      "Сыр Блю Чиз",
    ],
    sizes: [28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 12.54,
      fats: 10.07,
      carbohydrates: 34.15,
      calories: 277.39,
    },
  },
  {
    id: 15,
    title: "Пицца Пепперони",
    image: pepperoni,
    ingredients:
      "Много пепперони, много моцареллы, фирменный томатный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      {
        id: 5,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 6, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 7, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 10,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 14,
        image: pimiento,
        name: "Болгарский перец",
        weight: 17,
        price: 25,
      },
      {
        id: 15,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
    ],
    removeIngredients: ["Пепперони"],
    categories: ["Острая"],
    categoryImages: [fire],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 14.33,
      fats: 13.38,
      carbohydrates: 33.12,
      calories: 310.17,
    },
  },
  {
    id: 16,
    title: "Пицца Деревенская",
    image: country,
    ingredients:
      "Ветчина, копчёная курица, моцарелла, зеленый лук, маринованные огурцы, майонезный соус, фирменный томатный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 11,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 12, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 13, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 14,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 15,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 16,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Копченая Курица",
      "Ветчина",
      "Огурцы Маринованные",
      "Зеленый Лук",
      "Майонезный соус",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 11.56,
      fats: 12.67,
      carbohydrates: 31.21,
      calories: 285.12,
    },
  },
  {
    id: 17,
    title: "Пицца Ранч",
    image: ranch,
    ingredients:
      "Копчёная курица, ветчина, моцарелла, томаты, чеснок, соус ранч, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 10,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 14,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 15,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Томаты", "Копченая Курица", "Ветчина", "Чеснок"],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 11.42,
      fats: 16.11,
      carbohydrates: 32.63,
      calories: 321.23,
    },
  },
  {
    id: 18,
    title: "Пицца Жгучая Барбекю",
    image: sizzlingBarbecue,
    ingredients:
      "Пепперони, моцарелла, красный лук, халапеньо, болгарский перец, фирменный томатный соус, барбекю соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 11,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 12, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 13, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 14,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 15,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Перец Халапеньо",
      "Пепперони",
      "Лук Репчатый",
      " Болгарский Перец",
      "Барбекю соус",
    ],
    categories: ["Острая"],
    categoryImages: [fire],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 11.32,
      fats: 9.25,
      carbohydrates: 35.25,
      calories: 269.56,
    },
  },
  {
    id: 19,
    title: "Пицца Карбонара",
    image: carbonara,
    ingredients:
      "Много бекона, моцарелла, пармезан, томаты, сливки, свежий укроп, соус ранч, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 10, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 11, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 12,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 13,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 14,
        image: pimiento,
        name: "Болгарский перец",
        weight: 17,
        price: 25,
      },
      {
        id: 15,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 16,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 17,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 20,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Томаты", "Бекон", "Сыр Пармезан", "Укроп"],
    categories: ["Подходит для детей"],
    categoryImages: [bear],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 12.24,
      fats: 14.15,
      carbohydrates: 33.54,
      calories: 310.48,
    },
  },
  {
    id: 20,
    title: "Пицца 4 сыра",
    image: fourCheeses,
    ingredients:
      "Моцарелла, сыр блю чиз с голубой плесенью, фета, пармезан, соус ранч, тесто",
    price: 465,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      { id: 10, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 11, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 12,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 13,
        image: cheeseFeta,
        name: "Сыр Фета",
        weight: 10,
        price: 19,
      },
      {
        id: 14,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 15,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 18,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Сыр Пармезан", "Сыр Фета", "Сыр Блю Чиз"],
    categories: ["Без Мяса", "Подходит для Детей"],
    categoryImages: [leaf, bear],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 15.03,
      fats: 16.43,
      carbohydrates: 33.66,
      calories: 342.65,
    },
  },
  {
    id: 21,
    title: "Пицца Сырная",
    image: cheese,
    ingredients: "Моцарелла ,чеддер, фета, соус цезарь, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 14,
        image: cheeseFeta,
        name: "Сыр Фета",
        weight: 10,
        price: 19,
      },
      {
        id: 15,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 16,
        image: pimiento,
        name: "Болгарский Перец",
        weight: 17,
        price: 25,
      },
      {
        id: 17,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 18,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 19,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 20,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 21,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Сыр Фета", "Сыр Чеддер"],
    categories: ["Подходит для Детей"],
    categoryImages: [bear],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 14.3,
      fats: 13.9,
      carbohydrates: 35.49,
      calories: 324.23,
    },
  },
  {
    id: 22,
    title: "Пицца Мясная",
    image: meat,
    ingredients:
      "Пепперони, ветчина, копчёная курица, моцарелла, майонезный соус, фирменный томатный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      { id: 9, image: bacon, name: "Бекон", weight: 23, price: 45 },
      {
        id: 10,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 11,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 12, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 13, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 14,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 15,
        image: sauce,
        name: "Барбекю Соус на пиццу",
        weight: 25,
        price: 35,
      },
      {
        id: 16,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 17,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: [
      "Копченая Курица",
      "Ветчина",
      "Пепперони",
      "Майонезный соус",
    ],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 12.44,
      fats: 13.8,
      carbohydrates: 30.54,
      calories: 269.08,
    },
  },
  {
    id: 23,
    title: "Пицца Маргарита",
    image: margarita,
    ingredients:
      "Очень много моцареллы, томаты, фирменный томатный соус, тесто",
    price: 399,
    additionalIngredients: [
      {
        id: 0,
        image: mozzarella,
        name: "Сыр Моцарелла",
        weight: 30,
        price: 35,
      },
      {
        id: 1,
        image: cheeseSide,
        name: "Сырный Бортик",
        weight: 125,
        price: 119,
      },
      { id: 2, image: heart, name: "Пицца 'Сердце'", weight: 1, price: 95 },
      {
        id: 3,
        image: jalapeno,
        name: "Перец Халапеньо",
        weight: 12,
        price: 15,
      },
      { id: 4, image: tomato, name: "Томаты", weight: 25, price: 25 },
      { id: 5, image: champignon, name: "Шампиньоны", weight: 15, price: 25 },
      {
        id: 6,
        image: chickenSmoked,
        name: "Копченая Курица",
        weight: 25,
        price: 55,
      },
      { id: 7, image: ham, name: "Ветчина", weight: 21, price: 45 },
      { id: 8, image: pepperoni, name: "Пепперони", weight: 26, price: 45 },
      {
        id: 9,
        image: huntingSausages,
        name: "Охотничьи Колбаски",
        weight: 15,
        price: 35,
      },
      {
        id: 10,
        image: pickledCucumbers,
        name: "Огурцы Маринованные",
        weight: 20,
        price: 25,
      },
      { id: 11, image: onionBulb, name: "Лук Репчатый", weight: 8, price: 5 },
      { id: 12, image: onionGreen, name: "Зеленый Лук", weight: 8, price: 25 },
      {
        id: 13,
        image: cheeseParmesan,
        name: "Сыр Пармезан",
        weight: 15,
        price: 35,
      },
      {
        id: 14,
        image: cheeseFeta,
        name: "Сыр Фета",
        weight: 10,
        price: 19,
      },
      {
        id: 15,
        image: cheeseChedder,
        name: "Сыр Чеддер",
        weight: 26,
        price: 55,
      },
      {
        id: 16,
        image: cheeseBlue,
        name: "Сыр Блю Чиз",
        weight: 15,
        price: 55,
      },
      {
        id: 17,
        image: pimiento,
        name: "Болгарский Перец",
        weight: 17,
        price: 25,
      },
      {
        id: 18,
        image: pineapple,
        name: "Ананасы",
        weight: 20,
        price: 25,
      },
      {
        id: 19,
        image: dill,
        name: "Укроп",
        weight: 5,
        price: 15,
      },
      {
        id: 20,
        image: garlic,
        name: "Чеснок",
        weight: 8,
        price: 5,
      },
      {
        id: 21,
        image: sauce,
        name: "Ранч Соус на пиццу",
        weight: 23,
        price: 35,
      },
      {
        id: 22,
        image: sauce,
        name: "Горчичный Соус на пиццу",
        weight: 20,
        price: 35,
      },
      {
        id: 23,
        image: sauce,
        name: "Кетчуп Соус на пиццу",
        weight: 25,
        price: 35,
      },
    ],
    removeIngredients: ["Томаты"],
    categories: ["Без Мяса", "Подходит для детей"],
    categoryImages: [leaf, bear],
    sizes: [23, 28, 33],
    options: ["Тонкое", "Традиционное"],
    nutritionalValue: {
      proteins: 13.16,
      fats: 10.27,
      carbohydrates: 29.18,
      calories: 261.75,
    },
  },
];
